# MongoDB resmi image
FROM mongo:7

# Root kullanıcı bilgileri (opsiyonel)
ENV MONGO_INITDB_ROOT_USERNAME=admin
ENV MONGO_INITDB_ROOT_PASSWORD=secret

# Varsayılan port
EXPOSE 27017

# Başlangıç komutu
CMD ["mongod"]
