# PostgreSQL resmi image
FROM postgres:15

# Ortam değişkenleri (opsiyonel ama genelde kullanılır)
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=secret
ENV POSTGRES_DB=gotrue

# Varsayılan port
EXPOSE 5432

# Başlangıç komutu (Postgres image'ı için zaten varsayılan)
CMD ["postgres"]
