version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: gotrue
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
